### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by Mahendra7985**

### CODE REVIEW

**Comment by Mahendra7985** [comment]
I have added my details to contributors.md

**Comment by Aju100** [comment]
@Mahendra7985   sort your name alphabetically.

**Comment by Mahendra7985** [comment]
i have sorted

**Comment by Aju100** [comment]
@Mahendra7985  congrats

**Comment by Aju100** [comment]
@Mahendra7985 you have deleted the contributors.md file.

**Comment by Aju100** [comment]
@Mahendra7985  plz update with sorted ur name.

**Pull request merged**
