### PR TITLE
Added contribution

### PR DESCRIPTION
**Pull request by dpakgtm07**
Added to contribution. glad to be part of Hacktoberfest2020.
Thanks.

### CODE REVIEW

**Comment by Aju100** [comment]
@dpakgtm07  can you please manage your git conflict

**Comment by dpakgtm07** [comment]
Just resolves the conflict. Thanks

**Comment by Aju100** [comment]
@dpakgtm07 still it is.

**Comment by dpakgtm07** [comment]
But I resolved it. Anyway, will have a look again.

Dipak Gautam
From Mobile
Cell: +977-9808401600 / +977-9861446240
Reply at: mee.dip07@gmail.com

**Pull request merged**
