### PR TITLE
Updated Contributors.md

### PR DESCRIPTION
**Pull request by M-krishna**
Added my info in contributors.md

### CODE REVIEW

**Comment by Aju100** [comment]
@M-krishna  u have to resolve git conflict so it can be merged successfully.

**Comment by M-krishna** [comment]
@Aju100  Resolved merge conflict.

**Comment by Aju100** [comment]
@M-krishna  still there is. plz, go through it.

**Comment by M-krishna** [comment]
@Aju100 its resolved.

**Comment by Aju100** [comment]
great

**Pull request merged**
