### PR TITLE
update: revamp for hacktoberfest 2022

### PR DESCRIPTION
**Pull request by washbin**
cleared contributors.md, made some minor changes to readme and changed the assest pictures.

### CODE REVIEW

**Comment by Aju100** [comment]
@washbin don't delete the old one, just append your there name.

Also make a folder called archive where you move the old assets file, and update the root main directory asset content

**Comment by washbin** [comment]
@Aju100  I updated the branch as per your suggestions, check once for confirmation

**Comment by Aju100** [comment]
@washbin yo image xa ni past ko https://github.com/Hacktoberfest-Nepal/Your-First-PR/blob/master/assets/sagarmathahacktoberfest.png

yeslai chai euta folder archive ma rakhi deu

**Comment by Aju100** [comment]
Rest kura haru chai lgtm

**Comment by washbin** [comment]
@Aju100  assests vitra archive folder xa ani old assests tesmai xa, assests ko root ma chhai aile ko image matrai xa

**Comment by Aju100** [comment]
Thank you @washbin

**Pull request merged**
