### PR TITLE
Removed myself.

### PR DESCRIPTION
**Pull request by nimeshkavinda**

### CODE REVIEW

**Comment by Aju100** [comment]
@nimeshkavinda  why ?

**Comment by nimeshkavinda** [comment]
I had run into some issue for contributing to this repo. Because of the contribution I made, it shows 'Hacktoberfest-Nepal' as one of the organizations that I have contributed to in my activity overview. If you could remove myself from the repo, it would be huge help.

**Comment by nimeshkavinda** [comment]
Could you remove myself from this repo :relaxed:

**Comment by Aju100** [comment]
Hi @nimeshkavinda there, can you please update it. so we can remove you

**Comment by nimeshkavinda** [comment]
Hi, done. If this branch is of no use, removing the branch would do it i think 😊 sorry for the trouble

**Pull request closed without merging**
