### PR TITLE
updated

### PR DESCRIPTION
**Pull request by shubhamnag14**
updated the contributors.md and fill the details 
shubhamnag|Techno International Batanagar|Python, Flutter, Html,Css,Wordpress,Django,C++

### CODE REVIEW

**Comment by Aju100** [comment]
@shubhamnag14 can you please follow our guideline and update as info as requrement.

**Comment by shubhamnag14** [comment]
i have updateed the info according to the guidelines..

**Review by shubhamnag14 — COMMENTED** [review]
i have updated the contribution.md according to the guidelines

**Review by shubhamnag14 — COMMENTED** [review]
updated

**Review by shubhamnag14 — COMMENTED** [review]
updated

**Review by shubhamnag14 — COMMENTED** [review]
updated

**Comment by Aju100** [comment]
still not yet

**Comment by shubhamnag14** [comment]
tell the exact problem..plz

**Comment by Aju100** [comment]
@shubhamdsm actually the reason why u have git conflict is you didn't add origin of master branch and pull master branch. I prefer you to pull and manage it.

**Pull request merged**
